# Generated by Django 4.1 on 2023-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customeraccount_email_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='email_status',
            field=models.CharField(choices=[('Deactive', 'Deactive'), ('Active', 'Active')], default='Deactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='status',
            field=models.CharField(choices=[('Deactive', 'Deactive'), ('Active', 'Active')], default='Active', max_length=10),
        ),
    ]
