# Generated by Django 4.1 on 2023-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customeraccount_email_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='email_status',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='email_varify',
            field=models.BooleanField(default=False, editable=None),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='mobile_varify',
            field=models.BooleanField(default=False, editable=None),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='password',
            field=models.CharField(editable=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (0, 'Deactive')], default=1, max_length=10),
        ),
    ]
