# Generated by Django 4.1 on 2023-03-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customeraccount_email_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1),
        ),
    ]
