# Generated by Django 4.1 on 2023-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customeraccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='email_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='mobile_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
