# Generated by Django 4.1 on 2023-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customeraccount_email_otp_customeraccount_mobile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=0),
        ),
    ]
