# Generated by Django 4.1 on 2023-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customeraccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
