# Generated by Django 4.1 on 2023-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customeraccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='state',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='auth_token',
            field=models.CharField(blank=True, editable=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='email_varify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='mobile_varify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1),
        ),
    ]
