# Generated by Django 4.1 on 2023-03-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
