# Generated by Django 4.1 on 2023-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Pending', 'Pending'), ('Credit', 'Credit')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='posted_by',
            field=models.CharField(blank=True, default='DesignAdda', editable=False, max_length=50, null=True),
        ),
    ]
