# Generated by Django 4.1 on 2023-03-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_file_format_product_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url_status',
            field=models.SmallIntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='product_zip_status',
            field=models.SmallIntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Credit', 'Credit'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
