# Generated by Django 4.1 on 2023-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_product_url_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_choice',
            field=models.SmallIntegerField(choices=[(0, 'Free'), (1, 'Paid')], default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Pending', 'Pending'), ('Credit', 'Credit')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default='0'),
        ),
    ]
