# Generated by Django 4.1 on 2023-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_payment_choice_alter_category_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
