# Generated by Django 4.1 on 2023-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_mrp_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default='0'),
        ),
    ]
