# Generated by Django 4.1 on 2023-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_category_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
