# Generated by Django 4.1 on 2023-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Credit', 'Credit'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
