# Generated by Django 4.1 on 2023-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
